class CancellationToken:
    @property
    def cancelled(self) -> bool: ...

    @property
    def reason(self) -> str | None: ...

    async def wait(self) -> str: ...

    def raise_if_cancelled(self) -> None: ...


class CancellationSource:
    @property
    def token(self) -> CancellationToken: ...

    def cancel(self, reason: str) -> bool: ...
